"""Reads a client's report_config JSONB (sql/015_report_config.sql) -- the
per-client column/label/ROAS-threshold customization built for the web
Reports page -- so the Excel/DHR reports generated by the Python pipeline
match what that client sees on the web, instead of silently using a
different, fixed column set.
"""


def load_report_config(conn, client_id: str) -> dict | None:
    cur = conn.cursor()
    cur.execute("SELECT report_config FROM clients WHERE client_id = %s;", (client_id,))
    row = cur.fetchone()
    cur.close()
    return row[0] if row and row[0] else None
